//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 the random-ingress-operator authors.
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTemplateMetadata) DeepCopyInto(out *IngressTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTemplateMetadata.
func (in *IngressTemplateMetadata) DeepCopy() *IngressTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(IngressTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTemplateSpec) DeepCopyInto(out *IngressTemplateSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTemplateSpec.
func (in *IngressTemplateSpec) DeepCopy() *IngressTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(IngressTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIngress) DeepCopyInto(out *RandomIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIngress.
func (in *RandomIngress) DeepCopy() *RandomIngress {
	if in == nil {
		return nil
	}
	out := new(RandomIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RandomIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIngressCondition) DeepCopyInto(out *RandomIngressCondition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIngressCondition.
func (in *RandomIngressCondition) DeepCopy() *RandomIngressCondition {
	if in == nil {
		return nil
	}
	out := new(RandomIngressCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIngressList) DeepCopyInto(out *RandomIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RandomIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIngressList.
func (in *RandomIngressList) DeepCopy() *RandomIngressList {
	if in == nil {
		return nil
	}
	out := new(RandomIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RandomIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIngressSpec) DeepCopyInto(out *RandomIngressSpec) {
	*out = *in
	in.IngressTemplate.DeepCopyInto(&out.IngressTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIngressSpec.
func (in *RandomIngressSpec) DeepCopy() *RandomIngressSpec {
	if in == nil {
		return nil
	}
	out := new(RandomIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIngressStatus) DeepCopyInto(out *RandomIngressStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]RandomIngressCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NextRenewalTime != nil {
		in, out := &in.NextRenewalTime, &out.NextRenewalTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIngressStatus.
func (in *RandomIngressStatus) DeepCopy() *RandomIngressStatus {
	if in == nil {
		return nil
	}
	out := new(RandomIngressStatus)
	in.DeepCopyInto(out)
	return out
}
