on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          command: manifest

      - name: Checkout repo
        uses: actions/checkout@v2
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build image
        if: ${{ steps.release.outputs.releases_created }}
        run: make build-image

      - name: Login to GitHub Container Registry
        if: ${{ steps.release.outputs.releases_created }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image to Container registry
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          docker tag random-ingress-operator:latest ghcr.io/backmarket-oss/random-ingress-operator:${{ steps.release.outputs.tag_name }}
          docker push ghcr.io/backmarket-oss/random-ingress-operator:${{ steps.release.outputs.tag_name }}
